//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public int Id { get; set; }
        public System.DateTime DateStamp { get; set; }
        public string Message { get; set; }
        public int RecordCount { get; set; }
        public string UserName { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ObjectKey { get; set; }
        public string Action { get; set; }
    }
}
