//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class town6668Entities : DbContext
    {
        public town6668Entities()
            : base("name=town6668Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<hzBroker> hzBrokers { get; set; }
        public virtual DbSet<hzClient> hzClients { get; set; }
        public virtual DbSet<hzCommissionRate> hzCommissionRates { get; set; }
        public virtual DbSet<hzImport> hzImports { get; set; }
        public virtual DbSet<hzLockedRecord> hzLockedRecords { get; set; }
        public virtual DbSet<hzLog> hzLogs { get; set; }
    }
}
