//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzBroker
    {
        public hzBroker()
        {
            this.hzClients = new HashSet<hzClient>();
            this.hzCommissionRates = new HashSet<hzCommissionRate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string CfgNumber { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Ssn { get; set; }
        public decimal ConsCommission { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ICollection<hzClient> hzClients { get; set; }
        public virtual ICollection<hzCommissionRate> hzCommissionRates { get; set; }
    }
}
