//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzClient
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string GroupNo { get; set; }
        public string CorrectedGroupNumber { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public string CommissionSched { get; set; }
        public string Provider { get; set; }
        public string BrokerNumber { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateDropped { get; set; }
        public string MetaNote { get; set; }
    
        public virtual hzBroker hzBroker { get; set; }
    }
}
