//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzImport
    {
        public int Id { get; set; }
        public string Filename { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public System.DateTime DateAdded { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> DateLocked { get; set; }
    }
}
