//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class hzLockedRecord
    {
        public int Id { get; set; }
        public int ReportYear { get; set; }
        public int ReportMonth { get; set; }
        public int BrokerId { get; set; }
        public string AnnDate { get; set; }
        public string CommSch { get; set; }
        public string EffDate { get; set; }
        public string GroupName { get; set; }
        public string GroupNumber { get; set; }
        public string InsPeriod { get; set; }
        public string Product { get; set; }
        public double CommisionRate { get; set; }
        public double MonthlyCommission { get; set; }
        public double PremiumRecd { get; set; }
        public System.DateTime DateLocked { get; set; }
        public string UserLocked { get; set; }
    }
}
