//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawHorizon
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public string GroupName { get; set; }
        public string GroupNumber { get; set; }
        public string Product { get; set; }
        public string EffectiveDate { get; set; }
        public string RenewalDate { get; set; }
        public string InsuredPeriod { get; set; }
        public string C_CodeOneHundred { get; set; }
        public string C_CoastalCode { get; set; }
        public string CommissionSchedule { get; set; }
        public string C_TotalPremiumYTD { get; set; }
        public decimal PremiumReceived { get; set; }
        public decimal CommissionReceived { get; set; }
        public string Filename { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
    }
}
