//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cfgdata
{
    using System;
    using System.Collections.Generic;
    
    public partial class RawOxford
    {
        public int Id { get; set; }
        public int Month { get; set; }
        public int Year { get; set; }
        public string GroupCode { get; set; }
        public string GroupName { get; set; }
        public string InvoicePeriod { get; set; }
        public decimal AmountBilled { get; set; }
        public Nullable<decimal> PaymentReceived { get; set; }
        public Nullable<double> PercentOfPremium { get; set; }
        public int PEPM { get; set; }
        public Nullable<int> SubCountPEPM { get; set; }
        public Nullable<decimal> CommissionAmount { get; set; }
        public decimal AmountDue { get; set; }
        public string FileName { get; set; }
        public System.DateTime Created { get; set; }
        public bool Deleted { get; set; }
    }
}
